{{- $target := .Values.target -}}
{{- $releaseName := default .Release.Name .Values.appname -}}
{{- if hasKey .Values .Values.target }}
{{- range $key, $value := .Values }}
{{- if eq $key $target }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $releaseName }}
  labels:
    appli.kubernetes.io/name: {{ $releaseName }}
{{- end -}}
{{- end }}
{{- end }}