{{- $target := .Values.target -}}
{{- $releaseName := default .Release.Name .Values.appname -}}
{{- if hasKey .Values .Values.target }}
{{- range $key, $value := .Values }}
{{- if eq $key $target }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}
  labels:
    appli.kubernetes.io/name: {{ $releaseName }}
spec:
  type: {{ default "ClusterIP" $value.service.type }}
  ports:
    - port: {{ default "80" $value.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    appli.kubernetes.io/name: {{ $releaseName }}
{{- end -}}
{{- end }}
{{- end }}

